name: budget
description: "Simple budget tracker"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.6.1

dependencies:
  auto_route: ^10.0.0
  auto_size_text: ^3.0.0
  custom_sliding_segmented_control: ^1.8.5
  drift: ^2.25.1
  drift_flutter: ^0.2.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  grouped_list: ^6.0.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  shimmer: ^3.0.0
  syncfusion_flutter_charts: ^28.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  drift_dev: ^2.25.2
  auto_route_generator: ^10.0.1
  freezed: ^2.5.8
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4


flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false